# Generated by Django 3.2.2 on 2024-10-02 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0003_alter_profile_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default='X', max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format:Up to 10 digits allowed.', regex='^\\d{10,10}$')]),
        ),
    ]
