# Generated by Django 3.2.2 on 2024-10-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0005_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='message',
            new_name='reply_text',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='teacher',
            new_name='user',
        ),
    ]
