# Generated by Django 3.2.2 on 2024-10-22 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ComplaintMS', '0007_auto_20241022_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('School', models.CharField(choices=[('Vardhman Public School', 'Vardhman Public School'), ('Lions Public School', 'Lions Public School')], max_length=29)),
                ('contactnumber', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format:Up to 10 digits allowed.', regex='^\\d{10,10}$')])),
                ('type_user', models.CharField(choices=[('student', 'student'), ('grievance', 'grievance')], default='student', max_length=20)),
                ('Branch', models.CharField(choices=[('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default='X', max_length=29)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('Question 1', 'Question 1'), ('Question 0', 'Question 0'), ('Question 2', 'Question 2'), ('Question 3', 'Question 3'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
