# Generated by Django 3.2.2 on 2024-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0008_auto_20241022_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='questions',
            new_name='complaint',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('Can you help me understand the different career paths available for someone with my interests?', 'Can you help me understand the different career paths available for someone with my interests?'), ('What skills are most important for success in my desired career, and how can I develop them while still in school?', 'What skills are most important for success in my desired career, and how can I develop them while still in school?'), ('Are there any extracurricular activities or volunteer opportunities you recommend that align with my career goals?', 'Are there any extracurricular activities or volunteer opportunities you recommend that align with my career goals?'), ('How important is networking in my future career, and what steps can I take now to build connections?', 'How important is networking in my future career, and what steps can I take now to build connections?'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='School',
            field=models.CharField(choices=[('Woodbridge School', 'Woodbridge School'), ('Long View Public School', 'Long View Public School')], max_length=29),
        ),
    ]
